Set window title based on type of Inspector being shown
Ranchero-Software/NetNewsWire pull request #2396
Opened 2020-09-05 13:26 UTC by AngeloStavrow

This PR closes #2354.

Before showing the inspector window, this change checks what subclass of InspectorViewController class is being shown, then sets the window title accordingly:

- A `NothingInspectorViewController` (or unknown case) gets the window title "Inspector".
- A `FolderInspectorViewController`, `WebFeedInspectorViewController`, or `BuiltinSmartFeedInspectorViewController` gets the window title from the subclassed view controller's `nameTextField` property, if it exists; if it doesn't, it gets a generally-descriptive title like "Folder Inspector", "Feed Inspector", or "Smart Feed Inspector" instead.

Probably worth verifying:

- Clicking on a feed, folder, or smartfeed while the inspector is open changes the inspector's window title as expected
- Closing the inspector, clicking on another sidebar item, and then opening the inspector shows the correct window title.
- Opening the inspector and changing the name of the sidebar item (where possible) updates the inspector window's title.

👆 "Works on my machine" but please let me know if it doesn't for you!

2020-09-07 05:24 UTC, brentsimmons requested changes
Let’s take a different approach — let’s add a windowTitle var to the Inspector protocol. InspectorWindowController would then just ask the current Inspector for the windowTitle.

2020-09-07 19:09 UTC, AngeloStavrow commented
Shoot, rebasing this branch on the merged `mac-candidate` is including commits from #2397. 😕

2020-09-07 19:10 UTC, AngeloStavrow commented on Mac/Inspector/WebFeedInspectorViewController.swift
> +		windowTitle = feed.editedName ?? NSLocalizedString("Feed Inspector", comment: "Feed Inspector window title")
@brentsimmons I'm not 100% of this WebFeedInspectorViewController change. I'm tapping into the textfield delegate's controlTextDidChange method to make sure the window title updates as the feed's name is changed. If this seems like a reasonable approach, then I think this PR is ready for re-review!

2020-09-07 21:36 UTC, brentsimmons requested changes
I approve those changes — but would you redo this PR? It has changes from the dock unread count issue mixed in with it.

2020-09-08 11:21 UTC, AngeloStavrow commented
> I approve those changes — but would you redo this PR? It has changes from the dock unread count issue mixed in with it.

Yes, sorry about that! Closing this PR and replacing it with #2403.

2020-09-08 11:21 UTC, closed without merging